apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: postgres-dev
            imageRepo: 851725326403.dkr.ecr.us-east-1.amazonaws.com/postgres
            imageTag: "12.4-alpine"
            path: postgres
            targetRevision: main
          - appName: api-dev
            imageRepo: 851725326403.dkr.ecr.us-east-1.amazonaws.com/api-dev
            imageTag: 6e31da9-15
            path: api
            targetRevision: main
          - appName: web-dev
            imageRepo: 851725326403.dkr.ecr.us-east-1.amazonaws.com/web-dev
            imageTag: 6e31da9-17
            path: web
            targetRevision: main

  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{appName}}-image={{imageRepo}}:~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.tag: "~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-912853091
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: default
      source:
        repoURL: "git@gitlab.com:thanatisravankumar2003/application-helm-charts.git"
        targetRevision: "main"
        path: "{{path}}"
        helm:
          parameters:
            - name: "image.repository"
              value: "{{imageRepo}}"
            - name: "image.tag"
              value: "{{imageTag}}"
            - name: "replicaCount"
              value: "1"
          # valueFiles:
          #   - dev-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "dev"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
