apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qa-rb
subjects:
- kind: User
  name: qa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: qa
  apiGroup: rbac.authorization.k8s.io