helm:
  parameters:
  - name: image.repository
    value: 851725326403.dkr.ecr.us-east-1.amazonaws.com/postgres
    forcestring: false
  - name: image.tag
    value: 12.4-alpine
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 851725326403.dkr.ecr.us-east-1.amazonaws.com/postgres
    forcestring: true
