replicaCount: 1

image:
  repository: 851725326403.dkr.ecr.us-east-1.amazonaws.com/web-dev
  tag: "f6eeda5-2"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 1280Mi
  requests:
    memory: 256Mi